Repository googleapis/java-notebooks, pull requests merged in 2020-09, with the labels that each got.

#23 chore: regenerate README
  README.md
  synth.metadata
Labels: api: notebooks, cla: yes, context: none

#29 chore: regenerate templates
  .github/CODEOWNERS
  .github/workflows/auto-release.yaml
  .kokoro/release/stage.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#41 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: notebooks, automerge, cla: yes

#48 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#47 feat(v1beta1): add endpoint to OperationMetadata, upgrade_info to IsInstanceUpgradeableResponse
  .gitignore
  google-cloud-notebooks/src/main/java/com/google/cloud/notebooks/v1beta1/NotebookServiceClient.java
  google-cloud-notebooks/src/main/java/com/google/cloud/notebooks/v1beta1/package-info.java
  google-cloud-notebooks/src/test/java/com/google/cloud/notebooks/v1beta1/NotebookServiceClientTest.java
  grpc-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/NotebookServiceGrpc.java
  proto-google-cloud-notebooks-v1beta1/clirr-ignored-differences.xml
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/Instance.java
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/InstanceProto.java
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/IsInstanceUpgradeableResponse.java
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/IsInstanceUpgradeableResponseOrBuilder.java
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/NotebooksProto.java
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/OperationMetadata.java
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/OperationMetadataOrBuilder.java
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/SetInstanceAcceleratorRequest.java
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/SetInstanceAcceleratorRequestOrBuilder.java
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/SetInstanceMachineTypeRequest.java
  proto-google-cloud-notebooks-v1beta1/src/main/java/com/google/cloud/notebooks/v1beta1/SetInstanceMachineTypeRequestOrBuilder.java
  proto-google-cloud-notebooks-v1beta1/src/main/proto/google/cloud/notebooks/v1beta1/instance.proto
  proto-google-cloud-notebooks-v1beta1/src/main/proto/google/cloud/notebooks/v1beta1/service.proto
  synth.metadata
Labels: cla: yes, context: full

#50 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
