Repository googleapis/java-notebooks, pull requests merged in 2020-11, with the labels that each got.

#46 Add Integration Test cases
  google-cloud-notebooks/pom.xml
  google-cloud-notebooks/src/test/java/com/google/cloud/notebooks/v1beta1/it/ITNotebookServiceClientTest.java
Labels: api: notebooks, cla: yes

#75 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: notebooks, automerge, cla: yes

#76 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: notebooks, automerge, cla: yes

#77 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: notebooks, automerge, cla: yes, context: full

#78 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: notebooks, automerge, cla: yes, context: full

#81 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: notebooks, automerge, cla: yes, context: full

#83 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: notebooks, automerge, cla: yes, context: full

#84 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: notebooks, automerge, cla: yes, context: full

#85 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: notebooks, automerge, cla: yes, context: full, samples, samples
